NeoGym/Areas/Admin/Controllers/ClubsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NeoGym.Models;

namespace NeoGym.Areas.Admin.Controllers
{
    public class ClubsController : Controller
    {
        private NeoGymDbEntities db = new NeoGymDbEntities();

        // GET: Admin/Clubs
        public ActionResult Index()
        {
            return View(db.Club.ToList());
        }

        // GET: Admin/Clubs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Club.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            return View(club);
        }

        // GET: Admin/Clubs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Clubs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "id,name,link,description,image,price,meta,hide,order,datebegin")] Club club, HttpPostedFileBase img)
        {
            var path = "";
            var filename = "";
            if (ModelState.IsValid)
            {
                if (img != null)
                {
                    //filename = Guid.NewGuid().ToString() + img.FileName;
                    filename = img.FileName;
                    //Debug.WriteLine("file exists: "+ filename);
                    path = Path.Combine(Server.MapPath("~/Content/images/club"), filename);
                    img.SaveAs(path);
                    club.image = filename; //Lưu ý
                }
                club.datebegin = Convert.ToDateTime(DateTime.Now.ToShortDateString());
                db.Club.Add(club);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(club);
        }

        // GET: Admin/Clubs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Club.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            return View(club);
        }

        // POST: Admin/Clubs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,link,description,image,price,meta,hide,order,datebegin")] Club club, HttpPostedFileBase img)
        {
            var path = "";
            var filename = "";
            Product temp = db.Product.Find(club.id);
            if (ModelState.IsValid)
            {
                if (img != null)
                {
                    //filename = Guid.NewGuid().ToString() + img.FileName;
                    path = Path.Combine(Server.MapPath("~/Content/images/club"), filename);
                    img.SaveAs(path);
                    temp.image = filename; //Lưu ý
                }
                temp.name = club.name;
                temp.link = club.link;
                temp.meta = club.meta;
                temp.price = club.price;
                temp.description = club.description; //convert Tiếng Việt không dấu
                temp.hide = club.hide;
                temp.order = club.order;
                temp.datebegin = Convert.ToDateTime(DateTime.Now.ToShortDateString());
                db.Entry(temp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(club);
        }

        // GET: Admin/Clubs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Club.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            return View(club);
        }

        // POST: Admin/Clubs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Club club = db.Club.Find(id);
            db.Club.Remove(club);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NeoGym/Areas/Admin/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NeoGym.Areas.Admin.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Admin/Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

NeoGym/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NeoGym.Models;

namespace NeoGym.Areas.Admin.Controllers
{
    public class MenuController : Controller
    {
        private NeoGymDbEntities db = new NeoGymDbEntities();

        // GET: Admin/Menu
        public ActionResult Index()
        {
            return View(db.menu.ToList());
        }

        // GET: Admin/Menu/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            menu menu = db.menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // GET: Admin/Menu/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Menu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,link,meta,hide,order,datebegin")] menu menu)
        {
            if (ModelState.IsValid)
            {
                menu.datebegin = DateTime.Now;
                db.menu.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(menu);
        }

        // GET: Admin/Menu/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            menu menu = db.menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Admin/Menu/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,link,meta,hide,order,datebegin")] menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        // GET: Admin/Menu/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            menu menu = db.menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Admin/Menu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            menu menu = db.menu.Find(id);
            db.menu.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NeoGym/Controllers/NewsController.cs
using NeoGym.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NeoGym.Controllers
{
    public class NewsController : Controller
    {
        NeoGymDbEntities _db = new NeoGymDbEntities();
        // GET: News
        public ActionResult Index()
        {
            var v = from t in _db.News
                    where t.hide == true
                    orderby t.order
                    select t;
            return PartialView(v.ToList());
        }

        public ActionResult Detail(long id) {
            var v = from t in _db.News
                    where t.hide == true
                    && t.Id == id
                    orderby t.order
                    select t;
            return View(v.ToList());

        }
    }
}

NeoGym/Controllers/ProductController.cs
using NeoGym.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NeoGym.Controllers
{
    public class ProductController : Controller
    {
        NeoGymDbEntities _db = new NeoGymDbEntities();
        
        public ActionResult Index(string meta)
        {
            ViewBag.Title = "Sản Phẩm";
            if (meta == null)
            {
                var category_1 = from t in _db.Category
                                 where t.hide == true
                                 orderby t.order
                                 select t;
                return PartialView(category_1.ToList());
            }
            var category_2 = from t in _db.Category
                             where t.hide == true && t.meta == meta
                             orderby t.order
                             select t;

            return PartialView(category_2.ToList());
        }
        public ActionResult getProduct(long id) {
            var product = from t in _db.Product
                        where t.hide == true
                        && t.categoryId == id
                        select t;
            return PartialView(product.ToList());
        }

        public ActionResult Detail(string meta)
        {
            var product = from t in _db.Product
                          where t.hide == true
                          && t.meta == meta
                          select t;
            if (product == null)
            {
                return HttpNotFound(); // or redirect to an error page
            }
            return View(product.FirstOrDefault());
        }
    }
}

NeoGym/Areas/Admin/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Dashboard</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <h2 class="">Quản lí tin tức</h2>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "News")">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-tasks fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            @*<div class="huge">12</div>*@
                            <h2>Quản lí menu</h2>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "Menu")">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-shopping-cart fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            @*<div class="huge">Quản lí sản phẩm</div>*@
                            <h2>Quản lí sản phẩm</h2>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "Product")">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-support fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            @*<div class="huge">13</div>*@
                            <h2>Quản lí CLB</h2>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "Clubs")">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    
</div>